
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6

install:
    - make install

script:
  - make cover
  - make docs
  - make help

after_success:
    - coveralls
