
language: python
python:
    - 2.7
    - 3.4
    - 3.5


install:
    - travis_retry pip install coveralls jedi ipyparallel
    - travis_retry python setup.py install
    - cd metakernel_python
    - python setup.py install
    - cd ..

script:
  - ipcluster start -n=3 &
  - nosetests --exe -v --with-doctest --with-cov --cover-package metakernel;
  - ipcluster stop

after_success:
    - coveralls
