
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6

install:
    - make install
    - pip install coveralls

script:
  - make docs
  - make help
  - make cover

after_success:
    - codecov
