# After changing this file, check it on:
#   http://lint.travis-ci.org/


language: python
python:
    - 2.7
    - 3.3
    - 3.4


install:
    # install IPython according to their travis file:
    # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    # Pierre Carrier's PPA for PhantomJS and CasperJS
    - travis_retry sudo add-apt-repository -y ppa:pcarrier/ppa
    - time sudo apt-get update
    - travis_retry sudo apt-get install pandoc casperjs libzmq3-dev
    - travis_retry pip install -f https://nipy.bic.berkeley.edu/wheelhouse/travis jinja2 sphinx pygments tornado requests mock pyzmq jsonschema jsonpointer mistune

    - travis_retry git clone --recursive https://github.com/ipython/ipython
    - cd ipython
    - python setup.py install

    - cd ..
    - travis_retry pip install coveralls jedi 
    - travis_retry pip install pydot --allow-external pydot --allow-unverified pydot
    - travis_retry pip install pyparsing==1.5.7  --allow-external pyparsing --allow-unverified pyparsing
    - travis_retry python setup.py install
    - cd eval_kernel
    - travis_retry python setup.py install
    - cd ..

script:
    -  ipcluster start -n=3 &
    -  nosetests --exe -v --with-doctest metakernel
    -  ipcluster stop

script:
  - ipcluster start -n=3 &
  - nosetests --exe -v --with-doctest --with-cov --cover-package metakernel;
  - ipcluster stop

after_success:
    - coveralls
