name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Base
        uses: jupyterlab/maintainer-tools/.github/actions/setup-base@v1

      - name: Install dependencies
        run: |
          pip install coveralls
          make install

      - name: Run the tests
        run: |
          make docs
          make help
          make cover
